baseurl                 = "/"               # Your domain name. Must end with "/"
title                   = "Tyler Spaeth"
theme                   = "sam"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/origami.ico"
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
    homepage            = "Main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Everything must be made of paper."

# Metadata
    description         = "About Tyler Spaeth"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/avatar.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts"
    text = "Thoughts"

[[params.mainMenu]]
    link = "/portfolio"
    text = "Portfolio"

[[params.mainMenu]]
    link = "/about"
    text = "About me"
